coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%
ignore:
  - "benchmark/**"
flags:
  unit:
    paths:
      - src/
  com:
    paths:
      - src/
    carryforward: true
